version: '3.9'

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "4566:4566"
      - "4571:4571"
      - "8001:8001"
    environment:
      - SERVICES=dynamodb
      - DEFAULT_REGION=sa-east-1
      - AWS_ACCESS_KEY_ID=fakeAccessKeyId
      - AWS_SECRET_ACCESS_KEY=fakeSecretAccessKey
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - "./entrypoint.d:/docker-entrypoint-initaws.d"
