package br.com.poc.usercadastro.dynamo.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.Setter;

import java.util.UUID;

@Getter
@Setter
@AllArgsConstructor
@DynamoDBTable(tableName = "user-poc")
public class UserEntity {

    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = "uuid")
    private UUID uuid  ;

    @DynamoDBRangeKey(attributeName = "name")
    private String name;

    public UserEntity(String name) {
        this.name = name;
    }
}
